version: '3.8'

services:

  db:
    image: mysql:8.0.22
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=todo
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend  
    ports:
      - 3306:3306
    # restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=todo
      - DATABASE_PORT=3306
    networks: 
      - backend
      - frontend
    ports:
      - 8080:8080
    # restart: on-failure
    
# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:    